Feat/log table wip
Onix-Systems/flanksource-ui pull request #11
Opened 2022-02-08 11:26 UTC by AleksandrSekker

2022-02-08 11:45 UTC, JIamep20 requested changes

2022-02-08 11:45 UTC, JIamep20 commented on src/components/Logs/Table/LogsDropdown.js
> +export const LogsDropdown = ({ buttonTitle, items }) => (
непонятно, как использовать этот компонент. тебе нужно, что бы
1. в этот компонент ты можешь передать список  итемов и выбирать между ними.
2. в этом компоненте (возможно опционально) появляется итем "Create new ..." и по клику ты можешь выполнить что-то своё

2022-02-08 11:45 UTC, JIamep20 commented on src/components/Logs/Table/LogsDropdown.js
> +export const LogsDropdown = ({ buttonTitle, items }) => (
и вообще это listbox https://headlessui.dev/react/listbox

2022-02-09 17:55 UTC, JIamep20 requested changes

2022-02-09 17:55 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +              {/* <pre> */}
убери комментарии

2022-02-09 17:55 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +                      <button
ты уверен, что в thead рядом с th ячейками можно засунуть кнопку ?

2022-02-09 17:55 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +                    <tr key={uuidv4()} {...headerGroup.getHeaderGroupProps()}>
```suggestion
                    <tr key={index} {...headerGroup.getHeaderGroupProps()}>
```
ты знаешь, зачем вообще нужен key элементам? лучше уж индекс тогда и задушить претензии еслинта. но почте в примерах react-table я ничего такого не вижу ?

2022-02-09 17:55 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +                  action.handler(
action.handler раньше принимала массив выбранных логов и сейчас я не вижу в ней изменений. так что думаю правильней будет так

```suggestion
                  action.handler(selectedFlatRows.map(
                          (d) => d.original
                        ))
```

но заметь, что библиотека добавляет к итемам в этом массиве какое-то доп поле. наверное его лучше убрать

2022-02-09 17:55 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +  const data = useMemo(() => logs, []);
зависимость не указана. таблица не отобразить новые данные, если они обновятся

2022-02-09 17:55 UTC, JIamep20 commented on src/components/Logs/Table/IndeterminateCheckbox.js
> +          className="focus:ring-indigo-400 h-4 w-4 text-indigo-600 border-gray-300 rounded"
думаю это не единственное место, где может понадобитться такой чекбокс. лучше бы его засунуть в src/components и className передавать через пропсы

2022-02-09 18:00 UTC, saienkoo requested changes

2022-02-09 18:00 UTC, saienkoo commented on src/components/Logs/Table/logs-table.js
> +        Header: "Message",
почему timestamp в этом массиве не указана, но в таблице есть ?

2022-02-09 18:00 UTC, saienkoo commented on src/components/Logs/Table/logs-table.js
> +                <div className="mr-1 5">
так и должно быть?

2022-02-10 09:53 UTC, AleksandrSekker commented on src/components/Logs/Table/logs-table.js
> +        Header: "Message",
<img width="744" alt="Screen Shot 2022-02-10 at 11 50 02 AM" src="https://user-images.githubusercontent.com/32077311/153381821-d7437b0a-6e37-401e-a674-2517ceb512b9.png">
timestapm добавляеться здесь вместе с чекбоксами

2022-02-10 10:06 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +        Header: "Message",
есть какая-то по причина, по которой именно эта колонка должна быть добавлена таким образом, а не в массиве columns ?

2022-02-10 11:16 UTC, AleksandrSekker commented on src/components/Logs/Table/logs-table.js
> +        Header: "Message",
чекбокс должен быть в этой колонке, если рендерить в этом месте только чекбокс то между ними будет большое растояне, наверное можно в column рендерить вместе с чекбоксом но я пока не разобрался как это сделать

2022-02-10 11:35 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +        Cell: function dataItems({
почему не стрелочная функция?

2022-02-10 11:44 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +              original: { timestamp }
зачем такая большая деструктуризация? почему не оставить как было и не использовать row.original.timestamp?

зачем этим вобще заниматься? да, когда ты добавлял эти колонку через хук, value было пустым. но в массиве всех колонок приходит нормальное значение. 

поэтому нужно сначала расставлять на свои места, а потом настраивать

2022-02-10 12:47 UTC, saienkoo requested changes

2022-02-10 12:47 UTC, saienkoo commented on src/components/IndeterminateCheckbox/IndeterminateCheckbox.js
> +        />
```suggestion
        <input
          type="checkbox"
          ref={resolvedRef}
          {...rest}
        />
```

2022-02-10 12:47 UTC, JIamep20 commented on src/components/IndeterminateCheckbox/IndeterminateCheckbox.js
> +  ({ indeterminate, className, ...rest }, ref) => {
```suggestion
  ({ indeterminate, ...rest }, ref) => {
```

2022-02-10 12:47 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> +        Header: buttonHeader,
почему эта кнопка должна быть именно отдельной колонкой, а не в хедере message ?

2022-02-10 12:47 UTC, JIamep20 commented on src/components/Logs/Table/logs-table.js
> -import React, { useState } from "react";
таблица слишком широкая и ломает страницу даже при ширине 1200 пикселей

![image](https://user-images.githubusercontent.com/20907048/153411435-bfdd1bde-c56e-40c4-a679-2c46981f7793.png)

2022-02-21 16:12 UTC, merged