Feat/incident hypothesis builder wip
Onix-Systems/flanksource-ui pull request #7
Opened 2022-02-01 10:54 UTC by AleksandrSekker

2022-02-01 15:50 UTC, JIamep20 requested changes

2022-02-01 15:50 UTC, JIamep20 commented on src/icons/index.js
> +"region": timezone,
можно использовать иконки из react-icons ?

2022-02-01 17:18 UTC, JIamep20 requested changes

2022-02-01 17:18 UTC, saienkoo commented on tailwind.config.js
>          "warm-blue": "#CCDAF8",
![image](https://user-images.githubusercontent.com/20907048/152002078-03f88b6e-6b14-474d-846c-c48eb43bff71.png)

иконка state в модалке и в аккордионе не совпадает

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisDetails/index.js
> +      <div className="absolute top-8 right-20">
это вообще не хорошо. доделай компонент modal что бы в него можно было передавать соседей кнопки для закрытия. либо (если возможно) сделай так, что бы модалка вообще не рендерила кнопку, а обе кнопки ты передавал вместе со всем остальным как чилдренов. в любом случае сейчас я вижу что при нажатии на три точки есть эффект, а при нажатии на крестик нету - не хорошо

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/HypothesisNodeItem.js
> +      <Icon name={iconRightFirst} className="ml-3.5 mr-2.5" />
а если нужно будет 5 иконок? а если третью из пяти не нужно будет рендерить, что делать? это компонент с вполне себе конкретным назначением, можно попробовать сделать через пропсы (showMessageIcon, showSignalIcon) или дать больше контроля и позволить передавать нужные иконки сколько нужно и в нужном порядке

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/HypothesisNodeItem.js
> +        <Icon name={iconLeft} className="" />
react-icons

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/HypothesisNodeItem.js
> +      <span
если здесь будет строка из трех символов, область для клика будет слишком маленькая

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/index.js
> +  const getStatusIcon = (status) => {
посмотри как я сделал для таблицы инцидентов
1. для статусов - enums
2. для каких-либо соответствий - маппинги с фолбеками

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/index.js
> +        <div className="bg-dark-blue rounded-full p-2">
на дизайне там очевидно кнопка, у которой должны быть соответствующие стили

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/index.js
> +                        <p className="text-dark-gray mr-2.5 mt-0.5 font-medium">
```suggestion
                        <span className="text-dark-gray mr-2.5 mt-0.5 font-medium">
```

это не параграф, а просто надпись которая идет в одной строке с кнопкой.

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/index.js
> +                        <p className="text-dark-gray mr-2.5 mt-0.5 font-medium">
я думаю для одного инцидента в контенте аккордиона эта надпись должна появляться один раз, у тебя - для каждой гипотезы

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/index.js
> +                            <p className="text-dark-gray mr-2.5 mt-0.5 font-medium">
```suggestion
                            <span className="text-dark-gray mr-2.5 mt-0.5 font-medium">
```

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/index.js
> +                <Disclosure.Panel className="bg-light-blue p-5  mt-4 ml-1 rounded-8px border border-dashed">
![image](https://user-images.githubusercontent.com/20907048/152016600-63a3540d-a244-4878-b593-1d3ce3b0b230.png)

элементы не на одной линии

2022-02-01 17:18 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisNodeNew/index.js
> +                      </div>
это можно как-то вынести в отдельный компонент или может даже несколько? только если ты их понятно назовешь.

2022-02-10 13:29 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/EvidenceSection/index.js
>      return <LogsTable logs={evidence.evidence} title="" />;
![image](https://user-images.githubusercontent.com/20907048/153417878-b22a8f4b-4567-4ab2-9509-ebadaeff1d10.png)

2022-02-10 13:29 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/EvidenceSection/index.js
> +    return <TopologyCard topologyId={evidence.evidence.id} />;
карточка маленькая

2022-02-14 02:27 UTC, JIamep20 requested changes

2022-02-14 02:27 UTC, JIamep20 commented on tailwind.config.js
> +        "gray-dark": "#383A40",
подбери похожий цвет из доступных в tailwind. это уже перебор, что у нас dark-gray и тут же за ним gray-dark

2022-02-14 02:27 UTC, JIamep20 commented on src/components/HypothesisBuilder/index.js
> -        cardClass="w-full overflow-y-scroll"
ты уверен, что без `overflow-y-scroll` будет правильно работать? может лучше overflow-y-auto или как там он ?

2022-02-14 02:27 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisRootChildrenList/index.js
> +export const HypothesisRootChildrenList = ({ node, onTitleClick }) => (
лучше подели на два свойста - onIssueClick, onSolutionClick

2022-02-14 02:27 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/HypothesisDetails/index.js
> +      className={`text-lg font-medium text-gray-dark font-semibold ${className}`}
почему не clsx ?

2022-02-14 02:27 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/EvidenceSection/index.js
> -    return <LogsTable logs={evidence.evidence} title="" />;
`return <LogsTable logs={evidence.evidence} title="" />;`

2022-02-14 02:27 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/EvidenceSection/index.js
> -  return (
`return null`

2022-02-14 02:27 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CommentsSection/index.js
> +                      <p className="mt-0.5 text-medium-gray text-sm leading-5 font-normal">
новые цвета старайся не добавлять, если без них не обойтись, и пытайся подобрать из tailwindcss(но и тут тоже в крайности не бросайся). часто в фигре прямо так и написано - gray/900 например.

2022-02-14 02:27 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CommentsSection/index.js
> +          className="w-full border-gray-200 resize-none rounded-6px text-base leading-6 font-normal font-inter outline-none placeholder-darker-gray mb-2"
это text-gray-400. пересмотри все свои цвета здесь

2022-02-14 02:27 UTC, JIamep20 commented on src/components/EvidenceLogTable/EvidenceLogTable.js
> +export const EvidenceLogTable = ({ evidence }) => (
так то это не таблица получилась, хотя в названии компонента table. вообще, если я правильно понял, в конце этот компонент не понадобится.

2022-02-15 10:17 UTC, JIamep20 commented on tailwind.config.js
> +        "warm-green": "#AAA526",
куча новых цветов. все они нужны?

2022-02-15 11:52 UTC, AleksandrSekker commented on tailwind.config.js
> +        "warm-green": "#AAA526",
<img width="370" alt="Screenshot 2022-02-15 at 1 48 02 PM" src="https://user-images.githubusercontent.com/32077311/154056536-1b6e55e7-3b76-440b-80ae-ba7810c5164a.png">
они используются в компоненте HypothesisBar

2022-02-16 12:17 UTC, JIamep20 requested changes

2022-02-16 12:17 UTC, saienkoo commented on src/components/Avatar/index.js
> -  srcList: PropTypes.oneOf([
ты уверен, что теперь нету ошибки? по-моему оно ругалось что передается null

2022-02-16 12:17 UTC, saienkoo commented on src/components/Change/index.js
> +          <li key={uuidv4()}>
не нужно такое делать, вычисления таких хешей могут быть ресурсозатратными. лучше укажи eventIdx и заглуши варнинг от еслинта. и опять таки - тебе бы разобраться зачем именно указывается key. твой вариант еще хуже, чем использовать индекс мапа

2022-02-16 12:17 UTC, saienkoo commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +  const [nameValue, setNameValue] = useState("");
Это что? У тебя есть пекедж react-hook-form, который позволяет тебе строить формы используя его логику. Если с комментарием еще ладно - по идее он будет отправляться отдельно, то имя должно быть рядом со статусом в форме

2022-02-16 12:17 UTC, saienkoo commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +    const newNodeID = handleAddNode(nodePath);
эта функция вставляет в дерево новый стандартный итем и возвращает тебе id. используя react-query, мы хотим отойти от этого. что бы потом данные шли в одну сторону - данные получили, обработали и они пошли вниз по дереву компонентов. если делать как было у них - каждый дочерний компонент получается сам может редактировать всё дерево, и должен знать как это правильно сделать что бы ничего не сломалось

2022-02-16 12:17 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +    onHypothesisCreated();
модалка закроется раньше, чем гипотеза будет создана.

2022-02-16 12:17 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +  const onSubmit = () => {
```suggestion
  const onSubmit = async () => {
```

2022-02-16 12:17 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +      api.createMutation.mutate({
```suggestion
      await api.createMutation.mutateAsync({
```

2022-02-16 12:17 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +    const newNodeID = handleAddNode(nodePath);
```suggestion
    const newNodeID = uuidv4();
```

2022-02-16 12:17 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +  const statusItems = {
Это обязательно должно быть внутри компонента и пересчитываться на каждый рендер?

2022-02-16 12:17 UTC, JIamep20 commented on src/components/HypothesisBuilder/index.js
> +                  <CreateHypothesis
В итоге тебе не нужна будет handleAddNode и можно не использовать NestedHeirarchy в этом случае

2022-02-16 12:17 UTC, JIamep20 commented on src/components/HypothesisBuilder/index.js
> +            {(heirarchyProps) => (
я тебе вчера пытался обьяснить что если передавать сюда чилдренов в виде рендер-фунгкции, то можно получить сформированные пропсы, рендерить фрагмент и в него всё, что нужно. тоесть не рендерить NestedHeirarchy больше одного раза

2022-02-16 12:17 UTC, JIamep20 commented on src/pages/incident/incident-details.js
> +  const createMutation = useCreateHypothesisMutation({
посмотри что я скоро запушу - можно попытаться организовать optimistic updates. тоесть мутация добавляет новые данные в кеш до отправки запроса и если была ошибка - отменяет это. но делай это в самую последнюю очередь, и уточни у меня еще дополнительно перед этим

2022-02-16 12:17 UTC, JIamep20 commented on src/pages/incident/incident-details.js
> +    onSettled: () => {
я перенес эти колбеки в саму мутацию. посмотри

2022-02-16 12:35 UTC, AleksandrSekker commented on src/components/Avatar/index.js
> -  srcList: PropTypes.oneOf([
да, сейчас в консоле нет этой ошибки, оно ругалось из того что oneOf принимает значения,  а внутри типы данных
<img width="876" alt="Screenshot 2022-02-16 at 2 32 56 PM" src="https://user-images.githubusercontent.com/32077311/154265354-6945ce8e-1646-4bdc-9fc2-5327854ed8c8.png">

2022-02-16 12:42 UTC, AleksandrSekker commented on src/components/Change/index.js
> +          <li key={uuidv4()}>
не совсем понял что ты имеешь ввиду под зашлушить ворнинг, отключить это правило в этой строке или как?

2022-02-16 12:55 UTC, JIamep20 commented on src/components/Change/index.js
> +          <li key={uuidv4()}>
да, если ты в key передашь eventIdx и eslint начнет ругаться - заглуши варнинг только для этой строки

2022-02-16 14:27 UTC, AleksandrSekker commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +  const statusItems = {
treeFunctions уже не нужен,  хук useUser не может вызывать вне компонента (eslint ворнинг), а getNode использует данные с пропсов

2022-02-17 10:34 UTC, JIamep20 requested changes

2022-02-17 10:34 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +  const statusItems = {
Мой комментарий стоит только на одной строчке - обьявлении statusItems обьекта. в src/components/HypothesisBuilder/components/HypothesisDetails/index.js, откуда ты его похоже скопировал, он обьявлен и посчитан вне компонента

2022-02-17 10:34 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +          title: getValues("title"),
Почему в соседних строках разный подход? Либо везде getValues, либо везде значения с watch. Но надежнее будет getValues, поскольку он возвращает и стейта хука useForm актуальные данные. А значения с watch могут быть устаревшими, так как чисто теоретически нету гарантий, что между очередным изменением инпута и сабмитом формы обязательно будет хотя бы один рендер

2022-02-17 10:34 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
>            status: watchStatus
Судя по пот этой документации https://react-hook-form.com/api/useform/getvalues
возможно получится хранить данные в под-секциях и удобно получать их

стоит попытаться такое сделать 5-10 минут
```
  const { control, watch, getValues, setValue, handleSubmit } = useForm({
    defaultValues: {
      hypothesis: {
        status: node.status || Object.values(statusItems)[2].value,
        title: ""
      },
      evidence: {},
      comment: {
        text: ""
      }
    }
  });

const hypothesisValues = getValues("hypothesis");
      const evidenceValues = getValues("evidence");
      const commentValues = getValues("comment");

        <input
          id="name"
          type="text"
          placeholder="Type name"
          onChange={(e) => {
            setValue("hypothesis.title", e.target.value);
          }}
          value={nameValue}
          className="..."
        />
        <Dropdown
          control={control}
          name="hypothesis.status"
          className="mb-4 w-72"
          items={statusItems}
          label="State"
        />
```

2022-02-17 10:34 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> +    await handleComment(getValues("comments"));
Если if (api?.createMutation) не выполняется, то мы всёравно создаем комментарий? И к чему именно он создастся, если даже в случае успешного создания гипотезы, ты не пытаешься получить ее и как-то дальше использовать?

2022-02-17 10:34 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/CreateHypothesis/index.js
> -          onChange={(e) => setCommentTextValue(e.target.value)}
это обычный инпут без заморочек. посмотри в документации react-hook-form как можно компактнее нацепить на него логику

2022-02-21 16:58 UTC, JIamep20 requested changes

2022-02-21 16:58 UTC, JIamep20 commented on src/components/Details/index.js
> +export const Details = () => {
Что за Details? Абсолютно что это за компонент, как его использовать.

2022-02-21 16:58 UTC, JIamep20 commented on src/components/Details/index.js
> +const SingleValue = ({ children, ...props }) => (
Что за SingleValue? За что он отвечает? как его использовать? название должно описывать смысл компонент + в этом случае суффикс SingleValue
`IncidentPrioritySingleValue`

весь этот поток компонентов можно вынести а отдельный файл где-то рядом, например `select-components.js`

2022-02-21 16:58 UTC, JIamep20 commented on src/components/Details/RowDetail.js
> +export const RowDetail = ({ title, value }) => (
при переименовании Details это тоже нужно будет назвать получше

2022-02-21 16:58 UTC, JIamep20 commented on src/components/Details/index.js
> +    label: "Lindsay Walton",
в данных инцидента, которые возвращает апи, есть respondents, commander?

2022-02-21 16:58 UTC, JIamep20 commented on src/components/HypothesisBuilder/data.js
> +  created_by: []
это обьект должен быть

2022-02-21 16:58 UTC, JIamep20 commented on src/index.css
> +  .btn-round-xl {
на дизайне тоже 6 размеров?

2022-02-21 16:58 UTC, JIamep20 commented on src/pages/incident/incident-details.js
> +          <Details />
на дизайне эта форма в другом месте. почему она здесь?

2022-02-21 17:15 UTC, JIamep20 requested changes

2022-02-21 17:15 UTC, JIamep20 commented on src/components/Details/index.js
> +            name="respondents"
я не могу удалить выбранные итемы в этом селекте

2022-02-21 17:15 UTC, JIamep20 commented on src/components/Details/index.js
> +          <Select
не думаю, что в этом селекте стоит позволять текст в инпут для поиска

2022-02-21 17:15 UTC, JIamep20 commented on src/components/Details/index.js
> +    label: "Lindsay Walton",
коммандера ты сейчас уже вполне можешь получить, если дополнить запрос вот так
```
incident?id=eq.597806a0-4752-4a2f-87a4-bc5fff793f2b&select=*,commander_id(name,avatar),hypothesis!hypothesis_incident_id_fkey(*,created_by(name,avatar))
```

насчет респондентов не понятно, а обновление статуса и коммандера можно реализовать. делай это в последнюю очередь, когда всё остальное починишь

2022-02-22 09:05 UTC, AleksandrSekker commented on src/index.css
> +  .btn-round-xl {
<img width="616" alt="Screenshot 2022-02-22 at 10 58 19 AM" src="https://user-images.githubusercontent.com/32077311/155097924-b5047dbf-8428-4203-9589-825ad0e18ff8.png">
5 размеров, там стили для кнопки, для disabled кнопки и их размеры
<img width="1127" alt="Screenshot 2022-02-22 at 11 02 12 AM" src="https://user-images.githubusercontent.com/32077311/155098525-26df6e4d-a28d-483d-b347-c1fbfc106ce1.png">

2022-02-22 09:11 UTC, AleksandrSekker commented on src/pages/incident/incident-details.js
> +          <Details />
<img width="342" alt="Screenshot 2022-02-22 at 11 06 14 AM" src="https://user-images.githubusercontent.com/32077311/155099508-83ae7c1d-b398-4ac7-873f-b89aee00414a.png">
то есть эта форма должна быть вместо этой или как?

2022-02-22 09:16 UTC, AleksandrSekker commented on src/components/Details/index.js
> +            name="respondents"
когда селект выбраный итемы можно удалять как обычный текст, нажав backspace на клавиатуре. А как иначе это должно работать? в плане что на дизайне нет крестиков возле итемов или чего то похожего на удаление

2022-02-22 12:33 UTC, JIamep20 commented on src/pages/incident/incident-details.js
> +          <Details />
получается вместо этой, да

2022-02-22 12:34 UTC, JIamep20 commented on src/components/Details/index.js
> +            name="respondents"
backspace не подойдет, если у тебя 10 выбранных юзеров, а удалить нужно первого. в react-select можно передать свойство, что бы он не удалял выбранные итемы из меню

2022-02-22 13:02 UTC, JIamep20 requested changes

2022-02-22 13:02 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +  const commandersArray = useMemo(
добавь комментарий
// Temporary mock, in the future you need to replace it with an array of real users received from the api

2022-02-22 13:02 UTC, saienkoo commented on src/components/IncidentDetails/data.js
> +export const personRespondents = [
добавь комментарий что это временные данные, пока не будет получаться список потенциальных респондеров с апи или откуда-то еще

2022-02-22 13:02 UTC, saienkoo commented on src/components/IncidentDetails/data.js
> +    value: "Lindsay Walton",
в value должны быть id, даже в dummy данных просто для наглядности

2022-02-22 13:02 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +      started: dayjs(incident.created_at).format("DD.MM.YYYY") || "01.01.2022",
```suggestion
      started: incident.created_at,
```

Слабо представляю себе сценарий, когда у полученного с апи инцидента не будет указано created_at значение. даже если там будет undefined - dayjs вернет текущее время и ты его отформируешь. а значит

1. твой фолбек на 01.01.2022 не имеет смысла
2. странный фолбек сам по себе. лучше уж "прочерк" указывать. но не в логике формы. в логике формы должны быть адекватные значения, а форматирование происходит уже во времея рендера в каждом конкретном случае

2022-02-22 13:02 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +            {getValues("started")}
```
const formatDate = (date, fallback = '-') => date ? dayjs(date).format(...) : fallback;
```

2022-02-22 13:02 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +      duration: dayjs(incident.created_at).fromNow() || "13 days",
фолбек непонятно о чем. мы тут уже с реальными данными работаем, а не просто верстаем. просто убери это, а уже в jsx можешь считать нужно значение

2022-02-22 13:02 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +        title="Commanders"
на дизайне и Commanders, и Respondents написаны во множественном числе. но у инцидента коммандер указан и он один, а значит сделай наверное что бы этот инпут можно было очистить - была та кнопочка-крестик. а дальше, имея два рабочих примера, кто-то доделает как нужно

2022-02-22 13:02 UTC, saienkoo commented on src/components/IncidentDetails/select-components.js
> +export const priorities = [
судя по названию в этом файле должны находиться только компоненты для селекта. перенеси в сам компонент или в data.js

2022-02-22 14:21 UTC, saienkoo requested changes

2022-02-22 14:21 UTC, JIamep20 commented on src/components/IncidentDetails/data.js
> +// Temporary mock, in the future you need to replace it with an array of real respondents received from the apis
так и задумано, что комментарий тут, а не над personRespondents ?

2022-02-22 14:21 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +  const formatDate = (date, fallback = "-") => {
зачем так сложно? если хочешь - можно где-то за пределами компонента создать обьект formatDateUtils и в нем две функции - toDate, toDucation. это должны быть чистые функции. дальше или просто используй их, или если результат их выполнения используется больше чем 1 раз - в useMemo засунь

2022-02-22 14:21 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +    const getDate = date ? dayjs(date).format("DD.MM.YYYY") : fallback;
почему название переменной getDate, если это не функция?

2022-02-22 14:21 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +  const formatDate = (date, fallback = "-") => {
почему ты уже который раз пытаешься сделать именно функцию, которая вызывается и что-то из себя возвращает, и потом вызываешь ее 2+ раз? а что, если ее прийдется потом вызвать 1000 раз в один рендер? что будет с производительностью?

2022-02-22 14:21 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +    const getDuration = date ? dayjs(incident.created_at).fromNow() : fallback;
почему название getDuration, если это не функция?
почему ты проверяешь date из аргументов, а в dayjs передаешь incident.created_at из внешнего скоупа?

2022-02-22 14:21 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +  const formatDate = (date, fallback = "-") => {
в общем - почитай что такое чистые функции, старайся функции создавать чистыми или хотя бы почище при возможности, так как их проще понять, тестировать и использовать.

ты должен был создать в каком-либо виде две такие функции и использовать:

```
const DATE_FORMAT = "DD.MM.YYYY";

const formatDate = ({ date, format = DATE_FORMAT, fallback = "-" }) =>
  date ? dayjs(date).format(format) : fallback;
const dateToDuration = ({ date, withoutSuffix = false, fallback = "-" }) =>
  date ? dayjs(date).fromNow(withoutSuffix) : fallback;
```

либо написать примерно такие useMemo()

```
  const watchCreatedAt = watch("created_at");

  const formattedCreatedAt = useMemo(
    () => (watchCreatedAt ? dayjs(watchCreatedAt).format(DATE_FORMAT) : "-"),
    [watchCreatedAt]
  );
  const formattedDuration = useMemo(
    () => (watchCreatedAt ? dayjs(watchCreatedAt).fromNow() : "-"),
    [watchCreatedAt]
  );
```

либо скомбинировать эти подходы

```
  const watchCreatedAt = watch("created_at");

  const formattedCreatedAt = useMemo(
    () => formatDate({ date: watchCreatedAt }),
    [watchCreatedAt]
  );
  const formattedDuration = useMemo(
    () => dateToDuration({ date: watchCreatedAt }),
    [watchCreatedAt]
  );
```

2022-02-22 14:21 UTC, saienkoo commented on src/components/IncidentDetails/index.js
> +      duration: incident.created_at,
```suggestion
      created_at: incident.created_at,
```

здесь должны быть данные инцидента. что там с них ты уже отрендеришь - другой вопрос. хоть и 10 надписей с одной created_at даты

2022-02-22 15:06 UTC, JIamep20 commented on src/components/HypothesisBuilder/components/EvidenceSection/index.js
> +              <FiDatabase className="h-10 w-10 text-gray-400 mx-auto" />
попробуй с фигмы экспортировать svg нужной иконки и сделать из этого компонент в src/omponents/src-icons

https://www.sanity.io/guides/import-svg-files-in-react#c125367dce7c

2022-02-23 10:35 UTC, JIamep20 requested changes

2022-02-23 10:35 UTC, JIamep20 commented on src/components/IncidentDetails/index.js
> +      <div className="-mt-1.5">
и какой в этом смысл? сделали статичные нижние отступы в виде паддингов, потом добавляя лишнюю разметку отрицательными паддингами сдвигаем элементы. ты представляешь, какая морока потом может быть тебе же что-то менять в этом через месяц?

не нужно вообще таким элементам делать свои отступы, потому что если понадобится отрендерить такую строку где-то в компактном месте - твой же pb-4 будет тебе мешать

2022-02-23 10:35 UTC, JIamep20 commented on src/components/IncidentDetails/index.js
> +          value={
```suggestion
          title="Status Page"
          className="mb-2.5"
          value={
```

2022-02-23 10:35 UTC, JIamep20 commented on src/pages/incident/incident-details.js
> +          {/* <div className="bg-white px-4 py-5  shadow sm:rounded-lg sm:px-6"> */}
удали закомментированное

2022-03-25 08:56 UTC, closed without merging